Inheritance based implementation for user code
Nimac0/SDL_Minigame pull request #55
Opened 2024-05-29 08:09 UTC by Nanogamer7

See issue #54

2024-05-30 09:42 UTC, Nanogamer7 commented
New file names might not be ideal, especially as they reuse old names for different purposes. This creates issues with git diffs

2024-06-13 20:03 UTC, Nimac0 requested changes

2024-06-13 20:03 UTC, Nimac0 commented on include/GameFactory.h
> +    }();
macro bad, go into the shame corner >:c

2024-06-13 21:24 UTC, Nanogamer7 commented on include/GameFactory.h
> +    }();
done (the shame part)

please review again
also check https://github.com/VEGO-Engine/chickengame/tree/beni

2024-06-13 21:58 UTC, Nimac0 commented on include/GameFactory.h
> +    }();
lgtm

2024-06-13 21:59 UTC, Nimac0 approved these changes

2024-06-13 22:01 UTC, merged